### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Marvin1218**
@ziqishen-1575798

### CODE REVIEW

**Comment by Marvin1218** [comment]
@AlexSchuy

**Comment by ziqishen-1575798** [comment]
You did a good job, but you need to complete problem 3, 4 and the Non-continuous distribution part.

**Comment by ziqishen-1575798** [comment]
You did a great job so far, but you need to complete problem 3, 4 and the last part.

**Comment by AlexSchuy** [comment]
Hi, here are my comments for Lab 1:

**General Thoughts**

Remember that the document should be clearly readable -- describe what you're doing in words and provide explanations where requested. Please look at my comments on the slack regarding plot formatting and general tips.

**Problem 1**

Fine.

**Problem 2**

You don't need to calculate the pdf by hand -- there are built-in functions in scipy.stats.

**Problem 3**

Remember that this is considering the background distribution only. For b., an appropriate question would be something like, "What is the probability that I make a measurement at least as large as my observation, assuming the background distribution is true?" For c., you're integrating the background distribution, not the signal distribution.

**Problem 4**

Missing.

**Problem 5**

Missing.

**Pull request merged**
